import { administration } from '@Api/admin/endpoints';
import type { AdminRole, AdminStatus, AdminUser } from '@Api/admin/types';
import { BaseButton, Surface } from '@BaseComponents';
import { Box, HStack, Input, NativeSelect, SimpleGrid, Text, VStack } from '@chakra-ui/react';
import { interactiveStyles } from '@core/themes/motion';
import { Search } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import { AdminBadge, AdminField, AdminHeader, AdminLink, AdminPagination, AdminState } from '../../components/AdminUI';
import { useAdminQuery } from '../../hooks';
import { nameInitials, roleLabels, statusLabels } from '../../utils';

function UserRow({ user }: { user: AdminUser }) {
	const department = user.role === 'professor' ? user.professorProfile?.department?.name : user.staffProfile?.department?.name;
	return <HStack align='center' gap={4} flexWrap='wrap' py={4} borderBottomWidth='1px' borderColor='border.muted'><Box boxSize={11} display='grid' placeItems='center' flexShrink={0} borderRadius='full' bg='action.primarySubtle' color='action.primary' fontWeight='semibold' aria-hidden='true'>{nameInitials(user.name)}</Box><Box flex='1' minW='180px'><Text fontWeight='semibold' overflowWrap='anywhere'>{user.name}</Text><Text color='fg.muted' fontSize='sm' overflowWrap='anywhere'>{user.email}</Text><Text color='fg.muted' fontSize='xs' mt={1}>{department ?? user.studentProfile?.course?.name ?? 'Vínculo institucional não informado'}</Text></Box><HStack gap={2} flexWrap='wrap'><AdminBadge tone='accent'>{roleLabels[user.role]}</AdminBadge><AdminBadge tone={user.status === 'active' ? 'success' : user.status === 'pending' ? 'neutral' : 'warning'}>{statusLabels[user.status]}</AdminBadge></HStack><AdminLink to={`/admin/users/${user.id}`}>Gerenciar</AdminLink></HStack>;
}

export function UsersPage({ team = false }: { team?: boolean }) {
	const [params, setParams] = useSearchParams();
	const role = params.get('role') as AdminRole | null;
	const status = params.get('status') as AdminStatus | null;
	const issue = params.get('issue');
	const filters = { page: Math.max(1, Number(params.get('page')) || 1), q: params.get('q') || undefined, role: role && role in roleLabels ? role : undefined, status: status && status in statusLabels ? status : undefined, issue: issue === 'missing-profile' || issue === 'unassigned-professor' ? issue : undefined, team: team ? 'true' : undefined };
	const query = useAdminQuery(['users', filters], () => administration.users(filters));
	function filter(key: string, value: string) { setParams((current) => { const next = new URLSearchParams(current); value ? next.set(key, value) : next.delete(key); next.delete('page'); return next; }); }
	return <VStack align='stretch' gap={5}><AdminHeader title={team ? 'Equipe da instituição' : 'Usuários e acessos'} description={team ? 'Professores, secretaria e administradores com seus vínculos profissionais.' : 'Consulte cadastros e gerencie a identificação e o acesso de cada pessoa.'} action={<AdminLink to={team ? '/admin/team/new' : '/staff/students'}>{team ? 'Cadastrar equipe' : 'Cadastrar aluno'}</AdminLink>} /><Surface variant='panel' py={4}><VStack align='stretch' gap={4}><SimpleGrid columns={{ base: 1, lg: 'minmax(250px, 2fr) 1fr 1fr' }} gap={4}><form key={filters.q ?? ''} onSubmit={(event) => { event.preventDefault(); filter('q', String(new FormData(event.currentTarget).get('search') ?? '').trim()); }}><AdminField label='Buscar pessoas'><HStack w='full'><Input {...interactiveStyles.field} name='search' defaultValue={filters.q ?? ''} placeholder='Nome, e-mail ou usuário' maxLength={100} /><BaseButton type='submit' variant='secondary' aria-label='Buscar pessoas'><Search size={17} /></BaseButton></HStack></AdminField></form><AdminField label='Perfil'><NativeSelect.Root><NativeSelect.Field value={filters.role ?? ''} onChange={(event) => filter('role', event.target.value)}><option value=''>Todos os perfis</option>{(Object.entries(roleLabels) as Array<[AdminRole, string]>).filter(([key]) => !team || key !== 'student').map(([key, label]) => <option key={key} value={key}>{label}</option>)}</NativeSelect.Field><NativeSelect.Indicator /></NativeSelect.Root></AdminField><AdminField label='Situação'><NativeSelect.Root><NativeSelect.Field value={filters.status ?? ''} onChange={(event) => filter('status', event.target.value)}><option value=''>Todas as situações</option>{Object.entries(statusLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</NativeSelect.Field><NativeSelect.Indicator /></NativeSelect.Root></AdminField></SimpleGrid>{!!(filters.q || filters.role || filters.status || filters.issue) && <HStack justify='space-between' flexWrap='wrap'><Text color='fg.muted' fontSize='sm'>{filters.issue === 'missing-profile' ? 'Exibindo perfis incompletos' : filters.issue === 'unassigned-professor' ? 'Exibindo professores sem turma' : 'Filtros aplicados'}</Text><BaseButton size='sm' variant='subtle' onClick={() => setParams({})}>Limpar filtros</BaseButton></HStack>}</VStack></Surface><AdminState query={query} empty={query.data?.items.length === 0}><Surface variant='panel' py={2}>{query.data?.items.map((user) => <UserRow key={user.id} user={user} />)}</Surface>{query.data && <AdminPagination {...query.data} onChange={(page) => setParams((current) => { const next = new URLSearchParams(current); next.set('page', String(page)); return next; })} />}</AdminState></VStack>;
}
