import { BaseButton, EmptyStateCard, ErrorStateCard, Surface } from '@BaseComponents';
import { Box, Field, Heading, HStack, Skeleton, Text, VStack } from '@chakra-ui/react';
import { ArrowRight, ChevronLeft, ChevronRight, type LucideIcon } from 'lucide-react';
import type { ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { adminError } from '../utils';

export function AdminHeader({ title, description, action }: { title: string; description: string; action?: ReactNode }) {
	return <HStack justify='space-between' align='start' flexWrap='wrap' gap={4} py={2}><Box flex='1' minW='220px'><Text fontSize='xs' fontWeight='semibold' letterSpacing='0.1em' textTransform='uppercase' color='action.primary' mb={2}>Administração</Text><Heading as='h1' fontSize={{ base: '2xl', md: '3xl' }} lineHeight='1.2' letterSpacing='-0.025em'>{title}</Heading><Text mt={2} color='fg.muted' fontSize='sm' maxW='640px'>{description}</Text></Box>{action}</HStack>;
}
export function AdminSection({ title, description }: { title: string; description?: string }) { return <Box mb={5}><Heading as='h2' fontSize='lg'>{title}</Heading>{description && <Text fontSize='sm' color='fg.muted' mt={1}>{description}</Text>}</Box>; }
export function AdminIcon({ icon: Icon }: { icon: LucideIcon }) { return <Box display='inline-flex' w='fit-content' p={3} bg='action.primarySubtle' color='action.primary' borderRadius='xl' flexShrink={0}><Icon size={21} aria-hidden='true' /></Box>; }
export function AdminBadge({ children, tone = 'neutral' }: { children: ReactNode; tone?: 'neutral' | 'accent' | 'success' | 'warning' }) { return <Text as='span' display='inline-flex' px={2.5} py={1} borderRadius='full' fontSize='xs' fontWeight='semibold' bg={tone === 'accent' ? 'action.primarySubtle' : 'bg.muted'} color={{ neutral: 'fg.muted', accent: 'action.primary', success: 'status.success', warning: 'status.warning' }[tone]}>{children}</Text>; }
export function AdminLink({ to, children }: { to: string; children: ReactNode }) { return <BaseButton asChild variant='subtle' size='sm'><Link to={to}>{children}<ArrowRight size={15} aria-hidden='true' /></Link></BaseButton>; }
export function AdminStat({ title, value, icon, to }: { title: string; value: number; icon: LucideIcon; to: string }) { return <Surface variant='panel' interactive asChild><Link to={to}><HStack justify='space-between' align='start'><Box><Text fontSize='sm' color='fg.muted'>{title}</Text><Text fontWeight='bold' fontSize='3xl' mt={2}>{value.toLocaleString('pt-BR')}</Text></Box><AdminIcon icon={icon} /></HStack><Text color='action.primary' fontSize='xs' fontWeight='semibold' mt={3}>Consultar cadastros →</Text></Link></Surface>; }
export function AdminState({ query, empty, children }: { query: { isPending: boolean; isError: boolean; error: unknown; refetch: () => unknown }; empty?: boolean; children: ReactNode }) {
	if (query.isPending) return <VStack align='stretch' gap={3} role='status' aria-label='Carregando administração'><Text fontSize='sm' color='fg.muted'>Carregando…</Text>{[1, 2, 3].map((i) => <Skeleton key={i} height='100px' borderRadius='xl' />)}</VStack>;
	if (query.isError) return <ErrorStateCard eyebrow='Não foi possível carregar' title='Vamos tentar novamente?' description={adminError(query.error)} actionLabel='Tentar novamente' onAction={() => void query.refetch()} />;
	if (empty) return <EmptyStateCard title='Nenhum resultado encontrado' description='Não há registros para esta seleção. Ajuste os filtros ou volte à visão geral.' />;
	return children;
}
export function AdminPagination({ page, total, pageSize, onChange }: { page: number; total: number; pageSize: number; onChange: (page: number) => void }) { const pages = Math.max(1, Math.ceil(total / pageSize)); return <HStack as='nav' aria-label='Paginação' justify='space-between' flexWrap='wrap' gap={3} pt={3}><Text role='status' color='fg.muted' fontSize='sm'>{total} resultados · Página {page} de {pages}</Text><HStack><BaseButton variant='secondary' size='sm' disabled={page <= 1} onClick={() => onChange(page - 1)}><ChevronLeft size={16} aria-hidden='true' />Anterior</BaseButton><BaseButton variant='secondary' size='sm' disabled={page >= pages} onClick={() => onChange(page + 1)}>Próxima<ChevronRight size={16} aria-hidden='true' /></BaseButton></HStack></HStack>; }
export function AdminField({ label, children, required, hint }: { label: string; children: ReactNode; required?: boolean; hint?: string }) { return <Field.Root required={required}><Field.Label>{label}{required && <Field.RequiredIndicator />}</Field.Label>{children}{hint && <Field.HelperText>{hint}</Field.HelperText>}</Field.Root>; }
export function AdminFeedback({ error, isSuccess, message }: { error: unknown; isSuccess: boolean; message: string }) { return error ? <Text role='alert' fontSize='sm' color='status.error'>{adminError(error)}</Text> : isSuccess ? <Text role='status' fontSize='sm' color='status.success'>{message}</Text> : null; }
