export const stateCardSurfaceStyles = {
	position: 'relative',
	overflow: 'hidden',
	borderRadius: 'xl',
	border: '1px solid',
	borderColor: 'border.muted',
	bg: 'bg.surface',
	p: { base: '1.25rem', md: '1.5rem' },
	shadow: 'surface',
	_dark: {
		borderColor: 'border.muted',
		bg: 'bg.canvas',
		shadow: 'surface',
	},
	_before: {
		content: '""',
		position: 'absolute',
		inset: '-40px auto auto -30px',
		w: '180px',
		h: '180px',
		borderRadius: 'full',
		bg: 'action.primarySubtle',
		filter: 'blur(70px)',
		opacity: 0.9,
	},
	_after: {
		content: '""',
		position: 'absolute',
		inset: 'auto -50px -60px auto',
		w: '200px',
		h: '200px',
		borderRadius: 'full',
		bg: 'action.primarySubtle',
		filter: 'blur(75px)',
		opacity: 0.55,
	},
} as const;
