export const stateCardSurfaceStyles = {
	position: 'relative',
	overflow: 'hidden',
	borderRadius: '2xl',
	border: '1px solid',
	borderColor: 'cardBorderSoft',
	bg: 'cardSurfaceMuted',
	p: { base: 5, md: 6 },
	shadow: 'cardShadow',
	_before: {
		content: '""',
		position: 'absolute',
		inset: '-40px auto auto -30px',
		w: '180px',
		h: '180px',
		borderRadius: 'full',
		bg: 'accentSoft',
		filter: 'blur(70px)',
		opacity: 0.9,
	},
	_after: {
		content: '""',
		position: 'absolute',
		inset: 'auto -50px -60px auto',
		w: '200px',
		h: '200px',
		borderRadius: 'full',
		bg: 'blue.100',
		filter: 'blur(75px)',
		opacity: 0.55,
	},
} as const;
